# Generated by Django 4.2.13 on 2024-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_profile_address_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
