# Generated by Django 4.2.13 on 2024-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("birthday", models.DateField()),
                ("bio", models.TextField()),
                ("image", models.TextField()),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "actor",
                "verbose_name_plural": "actors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200, unique=True)),
                ("overview", models.TextField()),
                ("score", models.FloatField()),
                ("popularity", models.FloatField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("language", models.CharField(max_length=5)),
                ("released", models.DateField()),
                ("available", models.BooleanField(default=True)),
                ("keyword", models.TextField(default="")),
                ("image", models.TextField(default="")),
                (
                    "actors",
                    models.ManyToManyField(related_name="movie", to="main.actor"),
                ),
                (
                    "categories",
                    models.ManyToManyField(related_name="movie", to="main.category"),
                ),
            ],
            options={
                "verbose_name": "movie",
                "verbose_name_plural": "movies",
                "ordering": ["title"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="main_catego_name_5111b9_idx"),
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(fields=["name"], name="main_actor_name_e2469d_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["id", "slug"], name="main_movie_id_3483dc_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["title"], name="main_movie_title_508b1f_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["-created_at"], name="main_movie_created_d49518_idx"
            ),
        ),
    ]
