# Generated by Django 5.0.4 on 2024-05-10 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='actor/%Y/%M/%D')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_actor_name_e2469d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('score', models.FloatField()),
                ('popularity', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language', models.CharField(max_length=5)),
                ('released', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='movies/%Y/%M/%D')),
                ('actors', models.ManyToManyField(related_name='movies', to='main.actor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='main.category')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['id', 'slug'], name='main_movie_id_3483dc_idx'), models.Index(fields=['title'], name='main_movie_title_508b1f_idx'), models.Index(fields=['-created_at'], name='main_movie_created_d49518_idx')],
            },
        ),
    ]
