# Generated by Django 4.1.13 on 2024-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_created_at_category_updated_at_actor_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.TextField(),
        ),
    ]
