# Generated by Django 5.0.6 on 2024-05-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rechargecode_orderdetail_order_purchasedmovie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="item",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="profile",
        ),
        migrations.AlterUniqueTogether(
            name="purchasedmovie",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="purchasedmovie",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="purchasedmovie",
            name="profile",
        ),
        migrations.DeleteModel(
            name="RechargeCode",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderDetail",
        ),
        migrations.DeleteModel(
            name="PurchasedMovie",
        ),
    ]
